const data = [
    {
        id: 1,
        category: 'set',
        imgUrl: 'https://sushi-point.com.ua/uploads/product/normal/446x334xparty-set1-soka-v-podarok.jpg.pagespeed.ic.4JBNLyvDQx.webp',
        name: 'Филадельфия сет',
        price: 999,
        weight: 1170,
        pieces: 48,
        ingredients: 'Филадельфия 8шт, Ролл с лососем 6шт, Ролл с огурцом 6шт, Ролл с курицей 6шт, Банзай 8шт, Филадельфия кунсей 8шт, Спайси с копченой курицей 2шт, Спайси с тунцом 2шт',
    },
    {
        id: 2,
        category: 'set',
        imgUrl: 'https://sushi-point.com.ua/uploads/product/normal/446x334xset-1-kg.jpg.pagespeed.ic.9LsOSe5gES.webp',
        name: 'Сяке сет',
        price: 709,
        weight: 940,
        pieces: 40,
        ingredients: 'Филадельфия в кунжуте 8шт, Ролл с лососем 6шт, Ролл с огурцом 6шт, Ролл с курицей 6шт, Ролл с чукой 6шт, Калифорния с лососем 8шт, Нигири с лососем 6шт',
    },
    {
        id: 3,
        category: 'set',
        imgUrl: 'https://sushi-point.com.ua/uploads/product/normal/446x334xfiladelfiya-set.jpg.pagespeed.ic.xO-X6vGWIN.webp',
        name: 'Ясахи сет',
        price: 729,
        weight: 800,
        pieces: 32,
        ingredients: 'Филадельфия 8шт, Калифорния с угрем 8шт, Киото 8шт, Футомаки с лососем 8шт',
    },
    {
        id: 4,
        category: 'set',
        imgUrl: 'https://sushi-point.com.ua/uploads/product/normal/446x334xset-na-3-personi.jpg.pagespeed.ic.NB3WJvdEGf.webp',
        name: 'Салмон сет',
        price: 1199,
        weight: 1050,
        pieces: 33,
        ingredients: 'Филадельфия 8шт, Нигири с лососем 16шт, Филадельфия сяке 6шт, Спайси с тунцом 3шт',
    },
    {
        id: 5,
        category: 'set',
        imgUrl: 'https://sushi-point.com.ua/uploads/product/normal/446x334xset-2.jpg.pagespeed.ic.l0oFlVN79o.webp',
        name: 'Мини сет',
        price: 409,
        weight: 450,
        pieces: 18,
        ingredients: 'Филадельфия 8шт, Спайси с лососем 2шт, Калифорния 8шт',
    },
    {
        id: 6,
        category: 'roll',
        imgUrl: 'https://sushiya.ua/media/sushiya/images/products/cache/f/f/2/1/8/ff21837b7288b82eea2cf00d0e04f9d2a6097e05.webp',
        name: 'Филадельфия',
        price: 279,
        weight: 270,
        pieces: 8,
        ingredients: 'Лосось, сыр "Филадельфия", огурец, авокадо',
    },
    {
        id: 7,
        category: 'roll',
        imgUrl: 'https://sushiya.ua/media/sushiya/images/products/cache/b/5/2/9/e/b529e09deaf5369b669d09d8bdec18fb9c21b7a6.webp',
        name: 'Калифорния',
        price: 239,
        weight: 190,
        pieces: 8,
        ingredients: 'Лосось, майонез японский, огурец, авокадо, икра тобико',
    },
    {
        id: 8,
        category: 'roll',
        imgUrl: 'https://sushiya.ua/media/sushiya/images/products/cache/c/8/e/e/4/c8ee46c925105682ff963ef6a2741bbc0dd1c4fa.webp',
        name: 'Калифорния с угрем',
        price: 199,
        weight: 190,
        pieces: 8,
        ingredients: 'Угорь, огурец, авокадо, майонез японский, кунжут, соус "Унаги"',
    },
    {
        id: 9,
        category: 'roll',
        imgUrl: 'https://sushiya.ua/media/sushiya/images/products/cache/f/8/8/e/f/f88ef250e9787278b0b6ea881a49d12b2c79acbe.webp',
        name: 'Ролл с лососем',
        price: 89,
        weight: 110,
        pieces: 6,
        ingredients: 'Рис, лосось',
    },
    {
        id: 10,
        category: 'roll',
        imgUrl: 'https://sushiya.ua/media/sushiya/images/products/cache/f/e/8/9/e/fe89ed39afdcb50c138ef17005d32aa93e089fbf.webp',
        name: 'Ролл с курицей',
        price: 49,
        weight: 110,
        pieces: 6,
        ingredients: 'Копченная курица, майонез, зеленый лук',
    },
    {
        id: 11,
        category: 'sushi',
        imgUrl: 'https://sushiya.ua/media/sushiya/images/products/cache/1/0/d/5/6/10d565dd162de95f11e24c090b4bf0dfe4bb3db6.webp',
        name: 'Нигири с лососем',
        price: 39,
        weight: 33,
        pieces: 1,
        ingredients: 'Рис, лосось',
    },
    {
        id: 12,
        category: 'sushi',
        imgUrl: 'https://sushi-point.com.ua/uploads/product/normal/446x334xgunkan-spajs-unagi.jpg.pagespeed.ic.-YAWNVWRgG.webp',
        name: 'Спайси с курицей',
        price: 29,
        weight: 33,
        pieces: 1,
        ingredients: 'Острый соус "Спайси", копченая курица',
    },
    {
        id: 13,
        category: 'sushi',
        imgUrl: 'https://sushi-point.com.ua/uploads/product/normal/446x334xgunkan-spajs-tunets.jpg.pagespeed.ic.uR5xUflcxE.webp',
        name: 'Спайси с тунцом',
        price: 45,
        weight: 33,
        pieces: 1,
        ingredients: 'Острый соус "Спайси", тунец',
    },
    {
        id: 14,
        category: 'salad',
        imgUrl: 'https://sushiya.ua/media/sushiya/images/products/cache/d/7/5/6/3/d7563eb79f9612f4e9c4adf1f733852d50be031d.webp',
        name: 'Cалат Чука',
        price: 78,
        weight: 100,
        pieces: 1,
        ingredients: 'Водоросли Чука, ореховый соус, кунжут Классический салат японской кухни, подается с ореховым соусом собственного приготовления',
    },
    {
        id: 15,
        category: 'drinks',
        imgUrl: 'https://sushiya.ua/media/sushiya/images/products/cache/0/1/7/f/c/017fc23790e374506a5d747a91f3988bd74af6fa.webp',
        name: 'Coca Cola',
        price: 30,
        weight: 500,
        pieces: 1,
        ingredients: 'Безалкогольный напиток Pepsi',
    },
    {
        id: 16,
        category: 'drinks',
        imgUrl: 'https://sushiya.ua/media/sushiya/images/products/cache/d/4/c/9/c/d4c9ca124dbe6d9413c713ecd1c94d679884faec.webp',
        name: 'BonAqua',
        price: 19,
        weight: 500,
        pieces: 1,
        ingredients: 'Минеральная вода негазированная',
    },
    {
        id: 17,
        category: 'drinks',
        imgUrl: 'https://sushiya.ua/media/sushiya/images/products/cache/7/2/f/4/9/72f49ef185aef24d22cdba036f3c54854e50b659.webp',
        name: 'Имбирный лимонад',
        price: 39,
        weight: 500,
        pieces: 1,
        ingredients: 'Черная смородина, сахар, вода',
    },
    {
        id: 18,
        category: 'drinks',
        imgUrl: 'https://sushiya.ua/media/sushiya/images/products/cache/2/d/0/3/d/2d03d56244f67c134985e271af15d3af2c2daa16.webp',
        name: 'Сок Rich Апельсин',
        price: 59,
        weight: 1000,
        pieces: 1,
        ingredients: 'Персиковый сок',
    },
]

export default data;